services:
  mindscape-client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    env_file: ./.env
    ports:
      - $CLIENT_PORT:$CLIENT_PORT

  mindscape-server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file: ./.env
    environment:
      - DOCKERIZED='yes'
    ports:
      - $SERVER_PORT:$SERVER_PORT
